name: Hello World
on: [push]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Saludar
        run: echo "¡Hola desde GitHub Actions!"
      - name: Fecha
        run: echo "Fecha: $(date)"
      - name: Información
        run: |
          echo "OS: ${{runner.os}}"
          echo "Branch: ${{github.ref_name}}"
          echo "Commit: ${{github.sha}}"
