name: Hello World
on: [push]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Saludar
        run: echo "Hola desde GitHub Actions"
      - name: Informacion
        run: |
          echo "OS: linux"
          echo "Branch: main"
          echo "Commit: abc123"
